# Generated by Django 3.2 on 2021-05-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('hotel', 'Hotel'), ('apartment', 'Apartment')], default='apartment', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room_types', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=255)),
                ('hotel_room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='listings.hotelroomtype')),
            ],
        ),
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hotel_room_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='listings.hotelroomtype')),
                ('listing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='listings.listing')),
            ],
        ),
        # I think we can safely remove the AddConstraint/RemoveConstraint below
        migrations.CreateModel(
            name='BlockedDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booking_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='listings.bookinginfo')),
                ('hotel_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='listings.hotelroom')),
            ],
            options={
                'verbose_name_plural': 'Blocked days',
            },
        ),
        migrations.AddConstraint(
            model_name='blockeddays',
            constraint=models.UniqueConstraint(fields=('booking_info', 'hotel_room'), name='unique_blocking'),
        ),
        migrations.RemoveConstraint(
            model_name='blockeddays',
            name='unique_blocking',
        ),
        migrations.AddConstraint(
            model_name='blockeddays',
            constraint=models.UniqueConstraint(fields=('booking_info', 'hotel_room', 'start_date'), name='unique_blocking'),
        ),
        migrations.RemoveConstraint(
            model_name='blockeddays',
            name='unique_blocking',
        ),
        migrations.AlterField(
            model_name='blockeddays',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='listings.hotelroom', unique_for_date='start_date'),
        ),
        migrations.AlterField(
            model_name='blockeddays',
            name='booking_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='listings.bookinginfo', unique_for_date='start_date'),
        ),
        migrations.AlterField(
            model_name='blockeddays',
            name='booking_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='listings.bookinginfo'),
        ),
        migrations.AlterField(
            model_name='blockeddays',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='listings.hotelroom'),
        ),
        migrations.AddConstraint(
            model_name='blockeddays',
            constraint=models.UniqueConstraint(fields=('booking_info', 'hotel_room', 'start_date'), name='unique_blocking'),
        ),
        migrations.RemoveConstraint(
            model_name='blockeddays',
            name='unique_blocking',
        ),
    ]
